version: '3.8'

services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tfpm-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TFPMPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - tfpm-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "TFPMPassword123!" -C -Q "SELECT 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mssql-data:
    driver: local

networks:
  tfpm-network:
    driver: bridge
